name: "Deploy to GitHub Pages"
on:
  workflow_dispatch: {}
jobs:
  upload:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/upload-pages-artifact@v3"
        with:
          path: "strony"
  deploy:
    needs: "upload"
    runs-on: "ubuntu-latest"
    permissions:
      pages: "write"
      id-token: "write"
      contents: "read"
    environment:
      name: "github-pages"
    steps:
      - uses: "actions/deploy-pages@v4"
